// Enhanced Base Component Class
// Extends BaseComponent with module-aware capabilities for the modular architecture
// Provides automatic registration, dependency management, and enhanced lifecycle hooks

import BaseComponent from './BaseComponent.js';
import ModuleRegistry from '../utils/ModuleRegistry.js';

class EnhancedBaseComponent extends BaseComponent {
  /**
   * Create an enhanced base component with module capabilities
   * @param {Object} options - Component options
   * @param {string} [options.moduleName] - Override module name for registration
   * @param {string[]} [options.dependencies] - Array of dependency module names
   * @param {boolean} [options.autoRegister] - Auto-register component in module registry
   * @param {Object} [options.moduleMetadata] - Additional module metadata
   */
  constructor(options = {}) {
    super(options);
    
    // Module-specific options
    this.moduleOptions = {
      moduleName: options.moduleName || this.constructor.name,
      dependencies: options.dependencies || [],
      autoRegister: options.autoRegister !== false,
      moduleMetadata: options.moduleMetadata || {},
      ...options
    };
    
    // Module state
    this.moduleRegistry = null;
    this.dependencyInstances = new Map();
    this.isRegistered = false;
    
    // Initialize module system if enabled
    if (this.moduleOptions.autoRegister) {
      this.initializeModuleSystem();
    }
  }

  /**
   * Initialize the module system for this component
   */
  initializeModuleSystem() {
    try {
      // Get or create global module registry
      this.moduleRegistry = this.getModuleRegistry();
      
      // Auto-register this component if enabled
      if (this.moduleOptions.autoRegister && !this.isRegistered) {
        this.register();
      }
      
      // Import dependencies if specified
      if (this.moduleOptions.dependencies.length > 0) {
        this.importDependencies();
      }
      
    } catch (error) {
      console.warn(`Module system initialization failed for ${this.moduleOptions.moduleName}:`, error);
      // Continue without module features rather than failing
    }
  }

  /**
   * Get or create the global module registry
   * @returns {ModuleRegistry} - Module registry instance
   */
  getModuleRegistry() {
    // Try to get existing global registry
    if (typeof window !== 'undefined' && window.LearnimalsModuleRegistry) {
      return window.LearnimalsModuleRegistry;
    }
    
    // Create new registry if none exists
    const registry = new ModuleRegistry({
      debugMode: false,
      strictMode: false // Allow flexible registration during migration
    });
    
    // Store globally for sharing across components
    if (typeof window !== 'undefined') {
      window.LearnimalsModuleRegistry = registry;
    }
    
    return registry;
  }

  /**
   * Register this component in the module registry
   * @param {Object} options - Registration options
   * @returns {boolean} - Registration success
   */
  register(options = {}) {
    if (!this.moduleRegistry) {
      console.warn('Module registry not available for registration');
      return false;
    }
    
    try {
      const registrationOptions = {
        type: 'component',
        dependencies: this.moduleOptions.dependencies,
        version: '1.0.0',
        metadata: {
          className: this.constructor.name,
          autoGenerated: true,
          timestamp: new Date().toISOString(),
          ...this.moduleOptions.moduleMetadata
        },
        ...options
      };
      
      const success = this.moduleRegistry.register(
        this.moduleOptions.moduleName,
        this,
        registrationOptions
      );
      
      this.isRegistered = success;
      return success;
      
    } catch (error) {
      console.warn(`Failed to register component ${this.moduleOptions.moduleName}:`, error.message);
      return false;
    }
  }

  /**
   * Import and instantiate dependencies
   * @returns {Promise<Map>} - Map of dependency instances
   */
  async importDependencies() {
    if (!this.moduleRegistry || this.moduleOptions.dependencies.length === 0) {
      return this.dependencyInstances;
    }
    
    try {
      for (const depName of this.moduleOptions.dependencies) {
        if (!this.dependencyInstances.has(depName)) {
          const depModule = this.moduleRegistry.get(depName);
          
          if (depModule) {
            // If it's a class, instantiate it; otherwise use as-is
            const instance = typeof depModule.module === 'function' 
              ? new depModule.module()
              : depModule.module;
              
            this.dependencyInstances.set(depName, instance);
          } else {
            console.warn(`Dependency '${depName}' not found in registry`);
          }
        }
      }
    } catch (error) {
      console.warn(`Error importing dependencies for ${this.moduleOptions.moduleName}:`, error);
    }
    
    return this.dependencyInstances;
  }

  /**
   * Get a specific dependency instance
   * @param {string} dependencyName - Name of the dependency
   * @returns {*} - Dependency instance or null
   */
  getDependency(dependencyName) {
    return this.dependencyInstances.get(dependencyName) || null;
  }

  /**
   * Check if a dependency is available
   * @param {string} dependencyName - Name of the dependency
   * @returns {boolean} - True if dependency is available
   */
  hasDependency(dependencyName) {
    return this.dependencyInstances.has(dependencyName);
  }

  /**
   * Enhanced render method with dependency injection
   * @param {HTMLElement|string} [container] - Container element or selector
   * @returns {EnhancedBaseComponent} - Returns this for chaining
   */
  render(container) {
    // Ensure dependencies are loaded before rendering
    this.importDependencies()
      .then(() => {
        // Call parent render method
        super.render(container);
        
        // Emit module-aware events
        this.emitModuleEvent('componentRendered', {
          moduleName: this.moduleOptions.moduleName,
          dependencies: Array.from(this.dependencyInstances.keys())
        });
      })
      .catch(error => {
        console.warn(`Dependency loading failed during render for ${this.moduleOptions.moduleName}:`, error);
        // Continue with render even if dependencies fail
        super.render(container);
      });
    
    return this;
  }

  /**
   * Enhanced destroy method with module cleanup
   */
  destroy() {
    // Clean up dependencies
    this.dependencyInstances.clear();
    
    // Emit cleanup event
    this.emitModuleEvent('componentDestroyed', {
      moduleName: this.moduleOptions.moduleName
    });
    
    // Unregister from module registry if registered
    if (this.isRegistered && this.moduleRegistry) {
      try {
        this.moduleRegistry.unregister(this.moduleOptions.moduleName);
        this.isRegistered = false;
      } catch (error) {
        console.warn(`Failed to unregister ${this.moduleOptions.moduleName}:`, error);
      }
    }
    
    // Call parent destroy
    super.destroy();
    
    return this;
  }

  /**
   * Emit module-aware custom events
   * @param {string} eventName - Event name
   * @param {*} [detail] - Event detail data
   */
  emitModuleEvent(eventName, detail = {}) {
    const moduleDetail = {
      ...detail,
      moduleName: this.moduleOptions.moduleName,
      moduleType: 'component',
      timestamp: new Date().toISOString()
    };
    
    // Emit to element if available
    if (this.element) {
      this.emit(eventName, moduleDetail);
    }
    
    // Also emit to module registry for global listening
    if (this.moduleRegistry && typeof this.moduleRegistry.emit === 'function') {
      this.moduleRegistry.emit(eventName, moduleDetail);
    }
    
    return this;
  }

  /**
   * Get module information
   * @returns {Object} - Module information
   */
  getModuleInfo() {
    return {
      name: this.moduleOptions.moduleName,
      type: 'component',
      className: this.constructor.name,
      dependencies: this.moduleOptions.dependencies,
      isRegistered: this.isRegistered,
      loadedDependencies: Array.from(this.dependencyInstances.keys()),
      metadata: this.moduleOptions.moduleMetadata
    };
  }

  /**
   * Validate module integrity
   * @returns {Object} - Validation results
   */
  validateModule() {
    const results = {
      valid: true,
      errors: [],
      warnings: []
    };
    
    // Check if required dependencies are loaded
    for (const depName of this.moduleOptions.dependencies) {
      if (!this.dependencyInstances.has(depName)) {
        results.errors.push(`Required dependency '${depName}' not loaded`);
        results.valid = false;
      }
    }
    
    // Check if module is properly registered
    if (this.moduleOptions.autoRegister && !this.isRegistered) {
      results.warnings.push('Component should be registered but registration failed');
    }
    
    // Check if module registry is available
    if (!this.moduleRegistry) {
      results.warnings.push('Module registry not available');
    }
    
    return results;
  }

  /**
   * Static method to register a component class
   * @param {string} name - Component name
   * @param {Function} componentClass - Component class
   * @param {Object} options - Registration options
   * @returns {boolean} - Registration success
   */
  static register(name, componentClass, options = {}) {
    try {
      // Get or create global registry
      let registry;
      if (typeof window !== 'undefined' && window.LearnimalsModuleRegistry) {
        registry = window.LearnimalsModuleRegistry;
      } else {
        registry = new ModuleRegistry({ debugMode: false, strictMode: false });
        if (typeof window !== 'undefined') {
          window.LearnimalsModuleRegistry = registry;
        }
      }
      
      return registry.register(name || componentClass.name, componentClass, {
        type: 'component',
        ...options
      });
      
    } catch (error) {
      console.warn(`Static registration failed for ${name}:`, error);
      return false;
    }
  }

  /**
   * Static method to create and register a component
   * @param {Object} options - Component options including registration options
   * @returns {EnhancedBaseComponent} - Component instance
   */
  static create(options = {}) {
    const instance = new this(options);
    
    // Register if not already registered and auto-register is enabled
    if (!instance.isRegistered && instance.moduleOptions.autoRegister) {
      instance.register();
    }
    
    return instance;
  }

  /**
   * Static method to create component asynchronously with dependencies
   * @param {Object} options - Component options
   * @returns {Promise<EnhancedBaseComponent>} - Promise resolving to component instance
   */
  static async createAsync(options = {}) {
    const instance = new this(options);
    
    // Wait for dependencies to load
    await instance.importDependencies();
    
    return instance;
  }

  /**
   * Static method to get the global module registry
   * @returns {ModuleRegistry|null} - Module registry or null if not available
   */
  static getRegistry() {
    return (typeof window !== 'undefined' && window.LearnimalsModuleRegistry) || null;
  }
}

export default EnhancedBaseComponent;